# For more information: https://laravel.com/docs/sail
version: '3'
services:
    app:
        build:
            context: ./
            dockerfile: Dockerfile
        image: eveneer/busso
        container_name: app
        restart: unless-stopped
        volumes:
            - ./:/var/www
            - ./config/php/local.ini:/usr/local/etc/php/conf.d/local.ini

    webserver:
        build:
            context: .
            dockerfile: Dockerfile_Nginx
        image: eveneer/nginx
        container_name: webserver
        restart: unless-stopped
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - ./:/var/www
            - ./config/nginx/conf.d/:/etc/nginx/conf.d/
        depends_on:
            - app